"""
Strategy Base Class — Common interface for all trading strategies.

Every strategy inherits from this base and implements:
- `evaluate()` — score a security based on agent evidence + debate result
- `generate_signal()` — produce a trade candidate with entry/target/stop
- `check_exit()` — determine if a position should be closed

Strategies are regime-aware: each strategy declares which regimes it operates in.
The orchestrator selects active strategies based on the current market regime.

Key design principle: strategies are TRANSPARENT. Each one returns:
- A score (0-100) for the security
- The reasoning behind the score
- Specific entry, target, and stop levels
- Position sizing suggestion (risk % of portfolio)
- The evidence/indicators that triggered the signal

No black boxes. Every trade recommendation has an audit trail.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional
from enum import Enum


class SignalDirection(Enum):
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


@dataclass
class TradeSignal:
    """A trade signal generated by a strategy."""
    symbol: str
    strategy_name: str
    direction: SignalDirection
    score: float  # 0-100, how strong the signal is
    confidence: float  # 0-1, based on data quality and evidence
    entry_price: Optional[float] = None
    target_price: Optional[float] = None
    stop_price: Optional[float] = None
    position_size_pct: float = 0.0  # suggested % of portfolio
    risk_reward_ratio: float = 0.0
    reasoning: list[str] = field(default_factory=list)
    evidence: dict[str, float] = field(default_factory=dict)
    regime: str = ""
    as_of: Optional[date] = None
    expiry: Optional[date] = None  # signal expiry (optional)


@dataclass
class StrategyConfig:
    """Configuration for a strategy."""
    max_position_pct: float = 5.0  # max % of portfolio per position
    stop_loss_pct: float = 5.0  # stop loss below entry
    take_profit_pct: float = 15.0  # take profit above entry
    max_positions: int = 10  # max concurrent positions
    min_score: float = 60.0  # minimum score to generate a signal
    min_confidence: float = 0.3  # minimum confidence to generate a signal


class Strategy(ABC):
    """
    Base class for all trading strategies.

    Each strategy:
    1. Has a name, description, and applicable regimes
    2. Evaluates a security based on agent evidence + debate result
    3. Generates a trade signal with entry/target/stop/size
    4. Can check if an existing position should be exited
    """

    def __init__(
        self,
        name: str,
        description: str,
        applicable_regimes: list[str],
        config: Optional[StrategyConfig] = None,
    ):
        self.name = name
        self.description = description
        self.applicable_regimes = applicable_regimes
        self.config = config or StrategyConfig()

    @abstractmethod
    def evaluate(
        self,
        symbol: str,
        evidence: list[Any],  # list[DecisionEvidence]
        debate: Optional[Any],  # DebateResult
        market_data: dict[str, float],  # latest price, ATR, etc.
        regime: str,
    ) -> TradeSignal:
        """
        Evaluate a security and return a trade signal.

        Args:
            symbol: Ticker symbol
            evidence: Agent evidence from the orchestrator
            debate: Bull/bear debate result (if available)
            market_data: {price, atr, sma20, sma50, etc.}
            regime: Current market regime

        Returns:
            TradeSignal with direction, score, levels, and reasoning
        """
        pass

    def is_applicable(self, regime: str) -> bool:
        """Check if this strategy applies to the current regime."""
        return regime in self.applicable_regimes

    def _make_signal(
        self,
        symbol: str,
        direction: SignalDirection,
        score: float,
        confidence: float,
        market_data: dict[str, float],
        reasoning: list[str],
        evidence: dict[str, float],
        regime: str,
    ) -> TradeSignal:
        """Helper to construct a trade signal with calculated levels."""
        price = market_data.get("price", 0)
        atr = market_data.get("atr", price * 0.02)  # default 2% if no ATR

        signal = TradeSignal(
            symbol=symbol,
            strategy_name=self.name,
            direction=direction,
            score=min(100, max(0, score)),
            confidence=min(1.0, max(0.0, confidence)),
            reasoning=reasoning,
            evidence=evidence,
            regime=regime,
        )

        if direction == SignalDirection.LONG and price > 0:
            signal.entry_price = price
            # Use ATR for stop, but cap at config max
            atr_stop = atr / price * 100
            stop_pct = min(atr_stop * 1.5, self.config.stop_loss_pct)
            signal.stop_price = price * (1 - stop_pct / 100)
            signal.target_price = price * (1 + self.config.take_profit_pct / 100)
            signal.risk_reward_ratio = self.config.take_profit_pct / stop_pct if stop_pct > 0 else 0
            signal.position_size_pct = self._compute_position_size(score, confidence, stop_pct)

        elif direction == SignalDirection.SHORT and price > 0:
            signal.entry_price = price
            atr_stop = atr / price * 100
            stop_pct = min(atr_stop * 1.5, self.config.stop_loss_pct)
            signal.stop_price = price * (1 + stop_pct / 100)
            signal.target_price = price * (1 - self.config.take_profit_pct / 100)
            signal.risk_reward_ratio = self.config.take_profit_pct / stop_pct if stop_pct > 0 else 0
            signal.position_size_pct = self._compute_position_size(score, confidence, stop_pct)

        return signal

    def _compute_position_size(self, score: float, confidence: float, stop_pct: float) -> float:
        """
        Compute position size as % of portfolio.

        Larger size for higher scores and confidence, smaller for wider stops.
        Capped at config.max_position_pct.
        """
        if stop_pct <= 0:
            return 0.0

        # Base size from score
        score_factor = (score - 50) / 50  # 0-1 for scores 50-100
        confidence_factor = confidence
        risk_factor = min(1.0, 5.0 / stop_pct)  # smaller size for wider stops

        base_size = self.config.max_position_pct * score_factor * confidence_factor * risk_factor
        return max(0.0, min(self.config.max_position_pct, base_size))

    def _get_agent_scores(self, evidence: list[Any]) -> dict[str, dict[str, float]]:
        """Extract scores from agent evidence, organized by agent name."""
        result = {}
        for ev in evidence:
            if hasattr(ev, 'agent') and hasattr(ev, 'scores'):
                result[ev.agent] = ev.scores
        return result

    def _get_debate_scores(self, debate: Optional[Any]) -> dict[str, float]:
        """Extract debate scores if available."""
        if debate is None:
            return {}
        return {
            "bull_score": getattr(debate, 'bull_score', 50),
            "bear_score": getattr(debate, 'bear_score', 50),
            "net_score": getattr(debate, 'net_score', 0),
            "confidence": getattr(debate, 'confidence', 0),
        }
