"""
Position Monitor — Real-time position monitoring and alerting.

The position monitor continuously watches open positions for:
1. Stop loss hits — price reached stop level
2. Take profit hits — price reached target level
3. Trailing stop adjustments — move stop as price moves favorably
4. Drawdown alerts — position losing more than threshold
5. Time-based exits — position held too long
6. Correlation alerts — positions becoming correlated
7. Margin/liquidity warnings — insufficient buying power
8. Gap risk — overnight gap exposure

When an alert triggers, it generates an action (close, adjust stop, alert).
The Risk Engine evaluates the action before any execution.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone, date, timedelta
from typing import Optional, Any
from enum import Enum
import numpy as np

from marketmaster.execution.broker import BrokerPosition


class AlertType(Enum):
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    DRAWDOWN = "drawdown"
    TIME_EXIT = "time_exit"
    CORRELATION = "correlation"
    MARGIN_WARNING = "margin_warning"
    GAP_RISK = "gap_risk"
    REBALANCE = "rebalance"


class AlertAction(Enum):
    CLOSE = "close"
    ADJUST_STOP = "adjust_stop"
    NOTIFY = "notify"
    REDUCE_SIZE = "reduce_size"
    NO_ACTION = "no_action"


@dataclass
class PositionAlert:
    """An alert generated by the position monitor."""
    type: AlertType
    symbol: str
    action: AlertAction
    message: str
    current_price: float = 0.0
    trigger_price: float = 0.0
    severity: str = "info"  # info, warning, critical
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    strategy_name: str = ""
    suggested_stop: Optional[float] = None
    position: Optional[BrokerPosition] = None


@dataclass
class MonitoringResult:
    """Result of a monitoring cycle."""
    as_of: datetime
    total_positions: int
    alerts: list[PositionAlert] = field(default_factory=list)
    positions_checked: int = 0
    critical_count: int = 0
    warning_count: int = 0
    summary: str = ""


class PositionMonitor:
    """
    Monitors open positions and generates alerts.

    Usage:
        monitor = PositionMonitor()
        result = monitor.check_positions(
            positions=open_positions,
            current_prices={"AAPL": 195.0, "MSFT": 420.0},
            as_of=datetime.now(timezone.utc),
        )
    """

    def __init__(
        self,
        max_hold_days: int = 30,
        position_drawdown_alert_pct: float = 8.0,
        trailing_stop_activation_pct: float = 5.0,
        trailing_stop_distance_pct: float = 3.0,
        gap_threshold_pct: float = 3.0,
    ):
        self.max_hold_days = max_hold_days
        self.position_dd_alert_pct = position_drawdown_alert_pct
        self.trailing_activation_pct = trailing_stop_activation_pct
        self.trailing_distance_pct = trailing_stop_distance_pct
        self.gap_threshold_pct = gap_threshold_pct

    def check_positions(
        self,
        positions: list[BrokerPosition],
        current_prices: dict[str, float],
        entry_metadata: Optional[dict[str, dict]] = None,
        as_of: Optional[datetime] = None,
    ) -> MonitoringResult:
        """
        Check all open positions and generate alerts.

        Args:
            positions: Open positions from broker
            current_prices: {symbol → latest price}
            entry_metadata: {symbol → {entry_date, stop_price, target_price, strategy, entry_price}}
            as_of: Current timestamp

        Returns:
            MonitoringResult with all alerts
        """
        if as_of is None:
            as_of = datetime.now(timezone.utc)

        if entry_metadata is None:
            entry_metadata = {}

        result = MonitoringResult(
            as_of=as_of,
            total_positions=len(positions),
        )

        for pos in positions:
            meta = entry_metadata.get(pos.symbol, {})
            price = current_prices.get(pos.symbol, pos.current_price)

            if price <= 0:
                continue

            result.positions_checked += 1

            # ── Check 1: Stop Loss ──────────────────────────────────────
            stop = meta.get("stop_price", pos.stop_price if hasattr(pos, 'stop_price') else None)
            if stop and stop > 0:
                if pos.quantity > 0 and price <= stop:  # Long position
                    alert = PositionAlert(
                        type=AlertType.STOP_LOSS, symbol=pos.symbol,
                        action=AlertAction.CLOSE,
                        message=f"Stop loss triggered: {pos.symbol} at ${price:.2f} (stop: ${stop:.2f})",
                        current_price=price, trigger_price=stop,
                        severity="critical", strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)
                    result.critical_count += 1

                elif pos.quantity < 0 and price >= stop:  # Short position
                    alert = PositionAlert(
                        type=AlertType.STOP_LOSS, symbol=pos.symbol,
                        action=AlertAction.CLOSE,
                        message=f"Stop loss triggered (short): {pos.symbol} at ${price:.2f} (stop: ${stop:.2f})",
                        current_price=price, trigger_price=stop,
                        severity="critical", strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)
                    result.critical_count += 1

            # ── Check 2: Take Profit ────────────────────────────────────
            target = meta.get("target_price")
            if target and target > 0:
                if pos.quantity > 0 and price >= target:
                    alert = PositionAlert(
                        type=AlertType.TAKE_PROFIT, symbol=pos.symbol,
                        action=AlertAction.CLOSE,
                        message=f"Take profit reached: {pos.symbol} at ${price:.2f} (target: ${target:.2f})",
                        current_price=price, trigger_price=target,
                        severity="info", strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)
                elif pos.quantity < 0 and price <= target:
                    alert = PositionAlert(
                        type=AlertType.TAKE_PROFIT, symbol=pos.symbol,
                        action=AlertAction.CLOSE,
                        message=f"Take profit reached (short): {pos.symbol} at ${price:.2f} (target: ${target:.2f})",
                        current_price=price, trigger_price=target,
                        severity="info", strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)

            # ── Check 3: Trailing Stop ───────────────────────────────────
            entry_price = meta.get("entry_price", pos.entry_price)
            if entry_price and entry_price > 0 and pos.quantity > 0:
                gain_pct = (price - entry_price) / entry_price * 100

                if gain_pct >= self.trailing_activation_pct:
                    new_stop = price * (1 - self.trailing_distance_pct / 100)
                    if not stop or new_stop > stop:
                        alert = PositionAlert(
                            type=AlertType.TRAILING_STOP, symbol=pos.symbol,
                            action=AlertAction.ADJUST_STOP,
                            message=f"Trailing stop update: {pos.symbol} → ${new_stop:.2f} (gain: {gain_pct:.1f}%)",
                            current_price=price, trigger_price=new_stop,
                            severity="info", strategy_name=meta.get("strategy_name", ""),
                            suggested_stop=new_stop, position=pos,
                        )
                        result.alerts.append(alert)

            # ── Check 4: Position Drawdown ──────────────────────────────
            if entry_price and entry_price > 0:
                if pos.quantity > 0:
                    dd_pct = (entry_price - price) / entry_price * 100
                else:
                    dd_pct = (price - entry_price) / entry_price * 100

                if dd_pct > self.position_dd_alert_pct:
                    severity = "critical" if dd_pct > 15 else "warning"
                    alert = PositionAlert(
                        type=AlertType.DRAWDOWN, symbol=pos.symbol,
                        action=AlertAction.NOTIFY if severity == "warning" else AlertAction.REDUCE_SIZE,
                        message=f"Position drawdown: {pos.symbol} down {dd_pct:.1f}% from entry",
                        current_price=price, trigger_price=entry_price,
                        severity=severity, strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)
                    if severity == "warning":
                        result.warning_count += 1
                    else:
                        result.critical_count += 1

            # ── Check 5: Time-Based Exit ────────────────────────────────
            entry_date = meta.get("entry_date")
            if entry_date:
                if isinstance(entry_date, str):
                    entry_date = datetime.fromisoformat(entry_date)
                hold_days = (as_of.date() - entry_date.date()).days if hasattr(entry_date, 'date') else (as_of - entry_date).days

                if hold_days > self.max_hold_days:
                    alert = PositionAlert(
                        type=AlertType.TIME_EXIT, symbol=pos.symbol,
                        action=AlertAction.NOTIFY,
                        message=f"Position held {hold_days} days (max: {self.max_hold_days}) — consider exit",
                        current_price=price,
                        severity="warning", strategy_name=meta.get("strategy_name", ""),
                        position=pos,
                    )
                    result.alerts.append(alert)
                    result.warning_count += 1

            # ── Check 6: Unrealized P&L Status ──────────────────────────
            if pos.unrealized_pnl_pct < -10:
                alert = PositionAlert(
                    type=AlertType.DRAWDOWN, symbol=pos.symbol,
                    action=AlertAction.NOTIFY,
                    message=f"Large unrealized loss: {pos.symbol} at {pos.unrealized_pnl_pct:.1f}%",
                    current_price=price,
                    severity="critical", strategy_name=meta.get("strategy_name", ""),
                    position=pos,
                )
                result.alerts.append(alert)
                result.critical_count += 1

        # ── Summary ─────────────────────────────────────────────────────
        result.summary = (
            f"Monitored {result.positions_checked}/{result.total_positions} positions: "
            f"{result.critical_count} critical, {result.warning_count} warnings, "
            f"{len(result.alerts)} total alerts"
        )

        return result
