"""Alembic migration environment for MarketMaster.

Auto-generated by MarketMaster. Handles schema migrations.
"""

from alembic import context
from sqlalchemy import engine_from_config, pool

from marketmaster.config.settings import settings
from marketmaster.db.base import Base

# Import all models so they are registered with metadata
import marketmaster.db.models  # noqa: F401

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url_sync or settings.database_url)

target_metadata = Base.metadata


def run_migrations_offline():
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
